### ISSUE TITLE
Fix build failure on clean install

### ISSUE THREAD

**Issue by walkah** [fission-suite/testground-test-plans#1]
I got testground installed locally to try and learn more, but ran into some errors. Specifically, it looks like our test plans don't build cleanly. From what I can tell, this is the relevant part of the logs:

```
Step 15/22 : RUN cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}
 ---> Running in d60d9c2f0613
go: github.com/libp2p/go-libp2p@v0.19.2 requires
	github.com/ipfs/go-cid@v0.1.0: missing go.sum entry; to add it:
	go mod download github.com/ipfs/go-cid
May 12 19:43:36.866870	INFO	build failed	{"plan": "go-ds-s3", "groups": ["single"], "builder": "docker:go", "error": "docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 1"}
```

Also, if I try to just `go build` in the `go-ds-s3` folder, I get a bunch of missing dependency warnings too (I'm not sure yet if this is supposed to build independently). It looks like most of the missing deps are IPFS related things - perhaps go-ipfs was built also on machines where this is running?

**Comment by justindotpub** [comment]
Thanks @walkah.  I saw the errors and am iterating through them, stripping down to a bare bones test and building back up from there.  Closing this issue.
